/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { motion } from 'framer-motion-3d'
import React, { useRef } from 'react'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_moon.glb')
  return (
    <group {...props} dispose={null}>
      <motion.mesh
        // animate={{ scale: 1, x: 2, y: 2 }}
        // transition={{ duration: 2 }}
        castShadow
        receiveShadow
        geometry={nodes.Moon.geometry}
        material={nodes.Moon.material}
        rotation={[0, 0.54, -0.01]}
      />
    </group>
  )
}

useGLTF.preload('/models/low_poly_moon.glb')
