/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hazeletc (https://sketchfab.com/hazeletc)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-haunted-house-1b8a0044d259462396a831ba2d74f3c8
title: Low Poly Haunted House
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/haunted_house.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[1610.98, 0, 39.68]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={52.32}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Plane001_13_-_Default_0'].geometry}
              material={materials['13_-_Default']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Plane001_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Plane001_07_-_Default_0'].geometry}
              material={materials['07_-_Default']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Plane001_02_-_Default_0'].geometry}
              material={materials['02_-_Default']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Plane001_03_-_Default_0'].geometry}
              material={materials['03_-_Default']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane001_1_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            position={[1610.98, 0, 87.07]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={52.32}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object002_07_-_Default_0'].geometry}
              material={materials['07_-_Default']}
            />
          </group>
          <group
            position={[1610.98, 0, -136.06]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={52.32}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object003_07_-_Default_0'].geometry}
              material={materials['07_-_Default']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/haunted_house.glb')
