/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_moon.glb')
  // const { nodes, materials } = useGLTF('/models/low_poly_house.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon.geometry}
        material={nodes.Moon.material}
        rotation={[0, 0.54, -0.01]}
      />
    </group>
  )
}

useGLTF.preload('/models/low_poly_moon.glb')
